### ISSUE TITLE
Ne pas créer un nouveau compte et utiliser FranceConnect

### ISSUE THREAD

**Issue by guillett** [betagouv/signup-front#55]
Pour demander l'accès à des API, il faut créer un compte là ou il serait possible d'utiliser FranceConnect.

**Comment by rdubigny** [comment]
Un demandeur sur signup ne veut pas nécessairement utiliser son compte FranceConnect personnel pour une démarche qu'il effectue au nom d'une entreprise ou d'une adminitration. De plus, il n'en a pas l'obligation.

Je clos cette issue, n'hésite pas si tu as des suggestions.
